services:
  # Servicio de Base de Datos
  db:
    image: postgres:15-alpine  # Usamos una imagen ligera de PostgreSQL 15
    container_name: sidrac-container
    restart: always
    environment:
      POSTGRES_USER: sidrac
      POSTGRES_PASSWORD: adminpass
      POSTGRES_DB: sidracdb
    ports:
      - "5432:5432"  # Mapea el puerto del contenedor al de su máquina local
    volumes:
      - postgres_data:/var/lib/postgresql/data  # Persistencia de datos

# Definición del volumen para que los datos no se pierdan al reiniciar
volumes:
  postgres_data: